language: python
python:
  - 3.5
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install -r requirements-tests.txt
  - pip install coveralls
script:
  - py.test -v
after_script:
  - coveralls
